#ifndef SMIRVIDEOTOOL_CAMERA_ERRORS_H
#define SMIRVIDEOTOOL_CAMERA_ERRORS_H

typedef enum {
    CAM_SUCCESS_VAL = 0,
    CAM_INSUFFICIENT_MEMORY_ERROR = 100,
    CAM_EMPTY_FRAME_ERROR = 101,
    CAM_CAP_NOT_OPENED_ERROR = 102,
    CAM_CAP_WRONG_FPS_RES_ERROR = 103,
} Camera_Error_Types;

#endif //SMIRVIDEOTOOL_CAMERA_ERRORS_H
