#ifndef FFMPEG_VIDEO_STREAM_ENCODE_FFMPEG_VIDEO_ERRORS_H
#define FFMPEG_VIDEO_STREAM_ENCODE_FFMPEG_VIDEO_ERRORS_H

typedef enum {
    SUCCESS_VAL = 0,
    INSUFFICIENT_MEMORY_ERROR = 100,
    EMPTY_FRAME_ERROR = 101,
    CAP_NOT_OPENED_ERROR = 102,
    CAP_WRONG_FPS_RES_ERROR = 103,
}FFMPEG_Error_Types;

#endif //FFMPEG_VIDEO_STREAM_ENCODE_FFMPEG_VIDEO_ERRORS_H
